#!/usr/bin/perl -w

# You received this file as part of Finroc
# A framework for integrated robot control
# 
# Copyright (C) Finroc GbR (finroc.org)
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
#----------------------------------------------------------------------
# \file    finroc_create
#
# \author  Tobias Foehst
#
# \date    2012-01-17
#
#----------------------------------------------------------------------

use strict;

use Env '$FINROC_HOME';
use Env '$USER';
use XML::Simple;
use File::Basename;
use Data::Dumper;
use POSIX qw(strftime);
use open qw(:std :utf8);

use lib "$FINROC_HOME/scripts/perl";
use UI;
use FINROC::messages;
use FINROC::getopt;
use FINROC::sources;
use FINROC::components;


my $content_templates = XMLin("$FINROC_HOME/etc/content_templates.xml",
                              KeyAttr => { 'language' => 'name',
                                           'section' => 'name',
                                           'type' => 'name',
                                           'content' => 'language',
                                           'replace' => 'key'},
                              ForceArray => [ 'file', 'replace' ]);

sub FixMultiLineXMLEntry($)
{
    my ($key) = @_;
    $$content_templates{$key} = join "\n", map { s/^\s+//; $_ } split /\n/, $$content_templates{$key};
    $$content_templates{$key} =~ s/^\s//;
    $$content_templates{$key} =~ s/\s$//;
}

FixMultiLineXMLEntry "intro";
FixMultiLineXMLEntry "copyright";
FixMultiLineXMLEntry "license";

# Stupid ForceArray does not work again... Workaround: reorganize structure
if (exists ${$$content_templates{'content'}}{'language'})
{
    ${$$content_templates{'content'}}{${$$content_templates{'content'}}{'language'}}{'section'} = ${$$content_templates{'content'}}{'section'};
    delete ${$$content_templates{'content'}}{'language'};
    delete ${$$content_templates{'content'}}{'section'};
}
foreach (keys %{$$content_templates{'content'}})
{
    if (exists ${$$content_templates{'content'}}{$_}{'section'}{'name'})
    {
        ${$$content_templates{'content'}}{$_}{'section'}{${$$content_templates{'content'}}{$_}{'section'}{'name'}}{'type'} = ${$$content_templates{'content'}}{$_}{'section'}{'type'};
        delete ${$$content_templates{'content'}}{$_}{'section'}{'name'};
        delete ${$$content_templates{'content'}}{$_}{'section'}{'type'};
    }
}

foreach (keys %{$$content_templates{'content'}})
{
    ERRORMSG "Language $_ not declared. Content templates are not reachable.\n", unless exists $$content_templates{'language'}{$_};
}

# look for plugins that might extend our configuration
foreach my $language (keys %{$$content_templates{'language'}})
{
    my $language_folder = sprintf "$FINROC_HOME/%s", ${$$content_templates{'language'}}{$language}{'folder'};

    my $plugins_folder = sprintf "%s/plugins", $language_folder;
    $plugins_folder = sprintf "%s/org/finroc/plugins", $language_folder if $language eq "Java";

    next unless -d $plugins_folder;

    foreach my $plugin (map { chomp; $_ } `find "$plugins_folder" -mindepth 1 -maxdepth 1 -type d`)
    {
        my $content_templates_extension_file = sprintf "%s/etc/content_templates.xml", $plugin;
        if (-e $content_templates_extension_file)
        {
            my $content_templates_extension = XMLin($content_templates_extension_file,
                                                    KeyAttr => { 'section' => 'name',
                                                                 'type' => 'name',
                                                                 'content' => 'language',
                                                                 'replace' => 'key'},
                                                    ForceArray => [ 'file', 'replace' ]);

            foreach my $section (keys %{$$content_templates_extension{'section'}})
            {
                foreach my $type (keys %{$$content_templates_extension{'section'}{$section}{'type'}})
                {
                    ${$$content_templates{'content'}{$language}{'section'}{$section}{'type'}}{$type} = ${$$content_templates_extension{'section'}{$section}{'type'}}{$type};
                }
                foreach my $replace (keys %{$$content_templates_extension{'section'}{$section}{'replace'}})
                {
                    ${$$content_templates{'content'}{$language}{'section'}{$section}{'replace'}}{$replace} = ${$$content_templates_extension{'section'}{$section}{'replace'}}{$replace};
                }
            }
        }
    }
}

#print Dumper $content_templates;

#exit;



#my @content_types = ("Part", "Module", "Group", "Class", "Declarations, Functions, Utilities");
#
#my %content_types;
#
#foreach my $plugins_path (`find -L $FINROC_HOME/sources -type d -name "plugins"`)
#{
#    my $language = (split "/", substr($plugins_path, length "$FINROC_HOME/sources/"))[0];
#    print "$language\n";
#}



############################
##  Command line options  ##
############################

SetHelp undef, {
#    "-o [frame|content], --output=[frame|content]" => "Create new component frame or content",
#    "-f <type>, --frame=<type>" => ("Create new component frame, where <type> is one of\n".
#                                    "  finroc_project\n  finroc_library\n  finroc_plugin\n  finroc_tool\n  rrlib"),
#    "-c <type>, --content=<type>" => ("Create new content (file), where <type> if one of\n".
#                                      "  ".join "\n  ", map { s/, /_/g; lc } sort @content_types)
}, undef;

ParseCommandLine [ "output:s", "frame:s" ], sub {
#    if (defined GetCommandLineOption "output")
#    {
#        ERRORMSG "Possible values for --output: frame|content\n" unless (GetCommandLineOption "output") =~ /^(frame|content)$/;
#    }
};


####################
##  Setup dialog  ##
####################

UI::InitializeDialog "Finroc";

my $base_folder = $FINROC_HOME;

sub UpdateBaseFolder($)
{
    my ($xml_node) = @_;
    $base_folder .= "/$$xml_node{'folder'}" if exists $$xml_node{'folder'};
}


############################
##  Programming language  ##
############################


my $languages = $$content_templates{'language'};
my $language = UI::Menu("Programming Language",
                        undef,
                        { map { ( $_ => $$languages{$_}{'description'} ) } keys %$languages });

UpdateBaseFolder $$languages{$language};

my $language_folder = $base_folder;


###############
##  Section  ##
###############

my $sections = $$content_templates{'content'}{$language}{'section'};
my $section = UI::Menu("Section",
                       undef,
                       [ keys %$sections ]);

UpdateBaseFolder $$sections{$section};


####################
##  Content type  ##
####################

my $types = $$content_templates{'content'}{$language}{'section'}{$section}{'type'};
my $type = UI::Menu("Content Type",
                    undef,
                    { map { ( $_ => $$types{$_}{'description'} ) } keys %$types });

UpdateBaseFolder $$types{$type};


#########################
##  Files to generate  ##
#########################

my @optional_files = grep { defined $$_{'optional'} and $$_{'optional'} eq "true" } @{$$types{$type}{'file'}};
my @files = grep { not defined $$_{'optional'} or $$_{'optional'} eq "false" } @{$$types{$type}{'file'}};

my $selected_files = UI::CheckList("Optional Files",
                                   "Select optional files to generate.",
                                   [ map { $$_{'name'} } @optional_files ],
                                   [ map { $$_{'name'} } grep { defined $$_{'preselected'} and $$_{'preselected'} eq "true" } @optional_files ] );

foreach my $selected_file (@$selected_files)
{
    push @files, grep { $$_{'name'} eq $selected_file } @optional_files;
}

unless (@files)
{
    INFOMSG "Nothing to do!\n";
    exit;
}


#################
##  Subfolder  ##
#################

unless (defined $$sections{$section}{'members_as_subfolders'} and $$sections{$section}{'members_as_subfolders'} eq "false")
{
    my $member = UI::Menu("Member",
                          undef,
                          [ map { chomp; basename $_ } `find -L "$base_folder" -mindepth 1 -maxdepth 1 -type d -a ! -name ".*"` ]);
    $base_folder .= "/$member";
}


##############
##  Folder  ##
##############

my $folder = UI::SelectSubFolder $base_folder;
$folder = substr $folder, 1 + length $language_folder;


############
##  Name  ##
############

sub BreaksUpperCamelCase($)
{
    my ($string) = @_;
    map { return 1 if $_ eq " " } split //, $string;
    map { return 1 if $_ eq "_" } split //, $string;
    return 1 if substr($string, 0, 1) ne uc substr $string, 0, 1;
    return 0;
}

sub BreaksLowerCamelCase($)
{
    my ($string) = @_;
    map { return 1 if $_ eq " " } split //, $string;
    map { return 1 if $_ eq "_" } split //, $string;
    return 1 if substr($string, 0, 1) ne lc substr $string, 0, 1;
    return 0;
}

sub BreaksLowerCaseWithUnderscore($)
{
    my ($string) = @_;
    map { return 1 if $_ eq " " } split //, $string;
    map { return 1 if $_ ne lc $_ } split //, $string;
    return 0;
}

sub BreaksUpperCaseWithUnderscore($)
{
    my ($string) = @_;
    map { return 1 if $_ eq " " } split //, $string;
    map { return 1 if $_ ne uc $_ } split //, $string;
    return 0;
}

my $name;
while (1)
{
    $name = UI::InputText("Name",
                          sprintf("Enter name of new %s. (%s)", lc $type, $$types{$type}{'format'}),
                          '\S+',
                          undef);
    unless (length $name < 3)
    {
        last if $$types{$type}{'format'} eq "UpperCamelCase" and not BreaksUpperCamelCase $name;
        last if $$types{$type}{'format'} eq "lowerCamelCase" and not BreaksLowerCamelCase $name;
        last if $$types{$type}{'format'} eq "lower_case_with_underscore" and not BreaksLowerCaseWithUnderscore $name;
        last if $$types{$type}{'format'} eq "UPPER_CASE_WITH_UNDERSCORE" and not BreaksLowerCaseWithUnderscore $name;
    }
}


###################
##  Description  ##
###################

printf "Describe your new %s %s. Use one empty line to start a new paragraph and ctrl-d when you are done.\n", lc $type, $name;
my $description;
while (1)
{
    foreach (<STDIN>)
    {
        $description .= $_;
    }
    last if scalar @{[ split /\s/, $description ]} > 5;
    printf "Too short! Please give a serious description of your new %s.\n", lc $type;
}

##############
##  AUTHOR  ##
#############

my $author = ${[ split ",", ${[split ":", join "", map { chomp; $_ } `getent passwd \$USER`]}[4] ]}[0];
$author = UI::InputText("Author's full name", undef, '\S+( \S+)+'$author);


#############
##  FILES  ##
#############

my $filename = $name;
$filename = eval ${$$types{$type}}{'filename'} if exists ${$$types{$type}}{'filename'};
foreach (@files)
{
    $$_{'path'} = "$language_folder/$folder/$filename.$$_{'extension'}";
    die "$$_{'path'} already exists!\n" if -f $$_{'path'};
}


my %common_replacements = ( 'INTRO' => q("$$content_templates{'intro'}"),
                            'LICENSE' => q("$$content_templates{'license'}"),
                            'COPYRIGHT' => q("$$content_templates{'copyright'}"),
                            'AUTHOR' => q("$author"),
                            'DATE' => strftime("\"%Y-%m-%d\"", localtime time),
                            'NAME' => q("$name"),
#                            'SHORT_DESCRIPTION' => $short_description,
                            'DESCRIPTION' => q("$description"),
                            'FILE' => q("$folder/$filename.$$file{'extension'}"),
                            'INDENT_ONE_NAME' => q(" " x length $name),
                            'INDENT_TWO_NAMES' => q(" " x (2 * length $name)),
    );

if (exists ${$$languages{$language}}{'replace'})
{
    foreach (keys %{${$$languages{$language}}{'replace'}})
    {
        $common_replacements{$_} = qq(${$$languages{$language}}{'replace'}{$_}{'content'});
    }
}
if (exists ${$$sections{$section}}{'replace'})
{
    foreach (keys %{${$$sections{$section}}{'replace'}})
    {
        $common_replacements{$_} = qq(${$$sections{$section}}{'replace'}{$_}{'content'});
    }
}
if (exists ${$$types{$type}}{'replace'})
{
    foreach (keys %{${$$types{$type}}{'replace'}})
    {
        $common_replacements{$_} = qq(${$$types{$type}}{'replace'}{$_}{'content'});
    }
}

foreach my $file (@files)
{
    INFOMSG sprintf "Creating new file '%s' ... ", $$file{'path'};

    my %replacements;
    foreach (keys %common_replacements)
    {
        $replacements{$_} = eval $common_replacements{$_} or die;
    }

    my $template = `echo -n $$file{'template'}`;
    open TEMPLATE, "<$template" or die sprintf "Could not open template '%s': %s\n", $template, $!;
    open TARGET, ">$$file{'path'}" or die sprintf "Could not open target '%s': %s\n", $$file{'path'}, $!;
    foreach my $line (<TEMPLATE>)
    {
        while ($line =~ /%%([^%]+)%%/)
        {
            my $replacement = $1;
            $replacement = $replacements{$1} if exists $replacements{$1};
            if ($line =~ /^(.+)%%[^%]+%%/)
            {
                $replacement = join "\n$1", split /\n/, $replacement;
            }
            $line =~ s/%%[^%]+%%/$replacement/;
        }
        print TARGET $line;
    }
    close TARGET;
    close TEMPLATE;

    INFOMSG "done\n";
}

exit;


##my $output_type = lc $dialog->menu(
##    title => "What to create?",
##    text => "...",
##    list => [ "Content", "Classes, Modules, Groups, Parst or plain Files",
##              "Frame", "Components like projects, libraries, plugins or tools" ],
##    height => 9) or exit 0;
##
##if ($output_type eq "frame")
##{
##    my $finroc_or_rrlib = lc $dialog->menu(
##        title => "Create component",
##        text => "...",
##        list => [ "Finroc", "...",
##                  "RRlib", "..." ]) or exit 0;
##
##    my $component_type = "rrlib";
##    if ($finroc_or_rrlib eq "finroc")
##    {
##        $component_type = lc $dialog->menu(
##            title => "Create Finroc component",
##            text => "...",
##            list => [ "Project", "...",
##                      "Library", "...",
##                      "Plugin", "...",
##                      "Tool", "..." ]) or exit 0;
##        $component_type = "finroc_".$component_type;
##    }
##}
##
##
##if ($output_type eq "content")
##{
##    
##}





exit 0;
