#!/bin/bash

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
#----------------------------------------------------------------------
# \file    finroc_create_new_code_frame
#
# \author  unknown
#
# \date    unknown
#
#----------------------------------------------------------------------

test -f ./scripts/finroc_create_new_code_frame || echo "Please run this script in FINROC base directory"

SCRIPT_NAME=$1
NULL_ELEMENT=$2

if test -z $5; then
  echo usage:
  echo $SCRIPT_NAME base_path module_name 
  echo base_path must be a valid path relative to ${FINROC_HOME}
  exit
fi

DIR=$3 
DIR_NAME=$(echo $DIR | sed -e 's/\(.*\)\/$/\1/' -e 's/.*\/\(.*\)/\1/')
INCLUDE_DIR=$(echo $DIR | sed -e 's/^[^/]*\///' -e 's/[^/]*\///' -e 's/\/$//' -e 's/\//\\\//g')
NAMESPACE=$(echo sources/cpp/projects/test | cut -f 4 -d \/)
M_NAME=$4
PRE_NAME=$5

FIRST_LETTER=${M_NAME:0:1}

if [ $FIRST_LETTER == "m" ] || [ $FIRST_LETTER == "g" ] || [ $FIRST_LETTER == "p" ] ; then
    echo "I'll take care of the prefix myself ;-)"
    exit 1
fi

echo using path:   $DIR
echo using module: $M_NAME
AUTHOR=`finger -m $USER | grep Name | sed 's/L.*: *//'`
DATE=`date +%Y-%m-%d`
echo create sed-file
echo s/\<NAME\>/$M_NAME/g > $SCRIPT_NAME.sed  
echo s/\<DIRECTORY\>/$DIR_NAME/g >> $SCRIPT_NAME.sed
echo s/\<INCLUDE_DIRECTORY\>/$INCLUDE_DIR/g >> $SCRIPT_NAME.sed
echo s/\<SENTINEL\>/_${NAMESPACE}_${PRE_NAME}${M_NAME}_h_/g >> $SCRIPT_NAME.sed
echo s/\<NAMESPACE\>/${NAMESPACE}/g >> $SCRIPT_NAME.sed
echo s/\<AUTHOR\>/$AUTHOR/g >> $SCRIPT_NAME.sed 
echo s/\<DATE\>/$DATE/g >> $SCRIPT_NAME.sed  

cat $SCRIPT_NAME.sed

if test -d ${FINROC_HOME}/${DIR}; then

  # copy .h-null-file
  if [ -z "$6" ]; then 
    if test -e ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.h; then
      echo file ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.h already exists. Skipping it.
    else 
      echo creating file ${PRE_NAME}${M_NAME}.h in ${FINROC_HOME}/${DIR}
      sed -f $SCRIPT_NAME.sed < ${FINROC_HOME}/$NULL_ELEMENT.h.template > ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.h 
    fi
  fi

  # copy .cpp-null-file
  if test -e ${FINROC_HOME}/$NULL_ELEMENT.cpp.template; then
    if test -e ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.cpp; then
      echo file ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.cpp already exists. Skipping it.
    else 
      echo creating file ${PRE_NAME}${M_NAME}.cpp in ${FINROC_HOME}/${DIR}
      sed -f $SCRIPT_NAME.sed < ${FINROC_HOME}/$NULL_ELEMENT.cpp.template | sed -f $SCRIPT_NAME.sed> ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.cpp
    fi
  else
    echo file ${FINROC_HOME}/$NULL_ELEMENT.cpp.template does not exist. Skipping it.
  fi

  # copy .hpp-null-file
  if test -e ${FINROC_HOME}/$NULL_ELEMENT.hpp.template; then
    if test -e ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.hpp; then
      echo file ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.hpp already exists. Skipping it.
    else 
      echo creating file ${PRE_NAME}${M_NAME}.hpp in ${FINROC_HOME}/${DIR}
      sed -f $SCRIPT_NAME.sed < ${FINROC_HOME}/$NULL_ELEMENT.hpp.template | sed -f $SCRIPT_NAME.sed> ${FINROC_HOME}/${DIR}/${PRE_NAME}${M_NAME}.hpp
    fi
  else
    echo file ${FINROC_HOME}/$NULL_ELEMENT.hpp.template does not exist. Skipping it.
  fi

else
  echo path ${FINROC_HOME}/${DIR} does not exist.
fi

rm $SCRIPT_NAME.sed

exit 0
