#!/usr/bin/perl -w

# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
#----------------------------------------------------------------------
# \file    finroc_search
#
# \author  Tobias Foehst
#
# \date    2011-06-24
#
#----------------------------------------------------------------------

use strict;

use Env '$FINROC_HOME';
use Data::Dumper;

use lib "$FINROC_HOME/scripts/perl";
use FINROC::messages;
use FINROC::getopt;
use FINROC::sources;


############################
##  Command line options  ##
############################

SetHelp "<search_string>", undef, undef;

ParseCommandLine undef, undef;

# non-optional arguments
ERRORMSG sprintf "<search_string> not specified. Use %s --help for more information.\n", ScriptName unless defined $ARGV[0];

my $search_pattern = qr/$ARGV[0]/i;


#########################
##  Search components  ##
#########################

my %results;
my %components = GetAllComponents;
foreach my $name (keys %components)
{
    DEBUGMSG sprintf "component:\n%s\n", Dumper \$components{$name};

    my $match = 0;
    $match ||= $name =~ $search_pattern;
    $match ||= ${$components{$name}}{'description'} =~ $search_pattern if defined ${$components{$name}}{'description'};
    $results{$name} = $components{$name} if $match;
    next if $match;
}

DEBUGMSG sprintf "results:\n%s\n", Dumper \%results;

foreach my $key (sort keys %results)
{
    printf "%-34s %s\n", $key, defined $results{$key}{'description'} ? $results{$key}{'description'} : "<description not given>";
}



exit 0;
