#!/bin/bash
source script/mcasetenv '' &> /dev/null
make -C make_builder
rm Makefile
[ "x$FINROC_LOCAL" == "xno" ] && USE_SYSTEM_INSTALL=--usesysteminstall
java -Xmx256M -jar make_builder/dist/build.jar makebuilder.ext.finroc.FinrocBuilder --build=$FINROC_TARGET --combine $USE_SYSTEM_INSTALL
makeCall "$@"


