#!/bin/bash
[ -z $FINROC_HOME ] && source scripts/setenv ""
make -C make_builder
rm Makefile
java -Xmx256M -jar make_builder/dist/build.jar makebuilder.ext.finroc.FinrocBuilder --build=$FINROC_TARGET --systeminstall
make sysinstall "$@"
