#!/bin/bash
source script/mcasetenv '' &> /dev/null
make -C make_builder
rm Makefile
java -Xmx256M -jar make_builder/dist/build.jar makebuilder.ext.finroc.FinrocBuilder --build=$FINROC_TARGET --systeminstall
make sysinstall "$@"
