#!/bin/bash

# You received this file as part of Finroc
# A framework for integrated robot control
# 
# Copyright (C) Finroc GbR (finroc.org)
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
#----------------------------------------------------------------------
# \file    setenv
#
# \author  Tobias Foehst
# \author  Max Reichardt
#
# \date    2010-03-26
#
#----------------------------------------------------------------------

if [ ! -f ./scripts/setenv ] ; then
    echo "Please source this script in FINROC base directory"
    return 1
fi
eval `./scripts/tools/configure $@`

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

source ./scripts/tools/bash_completion
# enable tab completion for makeSafe and makeFast if system provides bash completion for GNU make
[ -f /etc/bash_completion.d/make ] && complete -F _make -o filenames makeSafe makeFast

return 0
