#!/bin/bash

test -f ./scripts/setenv || echo "Please source this script in FINROC base directory"
test -f ./scripts/setenv || return
eval `./scripts/configure $@`

export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
